version: '3.7'
services:
    mysql:
        container_name: mysql
        image: mysql:8.0.16
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./data:/var/lib/mysql
            - ./config:/etc/mysql/conf.d
        networks:
            - webnet
        restart: always

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            PHP_UPLOAD_MAX_FILESIZE: 100MB
        ports:
            - ${ADMIN_PORT}:80
        depends_on:
            - mysql
        networks:
            - webnet
        restart: always

networks:
    webnet:
        name: webnet
        driver: bridge
